server:
  port: 8081
jesque:
  enabled: true
  admin-enabled: true
  client-enabled: false
  worker-enabled: false
  async-event-enabled: false
  host: 192.168.99.100
  port: 6379
  password: 123456
  namespace: demoapp