logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%thread]){faint} %clr(%-40.40logger{39}){cyan} %L %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
server:
  port: 8081
jesque:
  enabled: true
  client-enabled: true
  worker-enabled: true
  admin-enabled: false
  async-event-enabled: false
  namespace: demo
  host: 192.168.99.100
  port: 6379
#  password: 123456
  pool-interval-in-millis: 500
  listen-queues: demoqueue
  workers-num: 5
  shutdown-await-millis: 30000
  log-event-enabled: false
  pool-worker-enabled: true